'use client';
import {useEffect,useRef,useState} from 'react';
const R=[
['Simple','Single','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/6548b2e8.jpg?h=1100&impolicy=fcrop&w=1800'],
['Doble','Double','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/93710469.jpg?h=1100&impolicy=fcrop&w=1800'],
['Triple','Triple','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/b46d55e9.jpg?h=1100&impolicy=fcrop&w=1800'],
['Familiar','Family','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/b4288bf3.jpg?h=1100&impolicy=fcrop&w=1800']] as const;
const S={arrival:'images/social/arrival.webp',breakfast:'images/social/breakfast.webp',games:'images/social/games.webp',family:'images/social/family.webp',morning:'images/social/morning.webp',guests:'images/social/guests.webp',ret:'images/social/return.webp'};
const Q=[
['Plaza Grande','3 cuadras','3 blocks','https://commons.wikimedia.org/wiki/Special:Redirect/file/Quito%20Plaza%20Independencia.jpg?width=1920'],
['Catedral Metropolitana','Centro Histórico','Historic Centre','https://commons.wikimedia.org/wiki/Special:Redirect/file/%28Catedral%20Metropolitana%2C%20Quito%29%20exterior%20%28pic.bb8%29.jpg?width=1920'],
['La Compañía','Barroco quiteño','Quito Baroque','https://commons.wikimedia.org/wiki/Special:Redirect/file/Quito%20Iglesia%20de%20La%20Compa%C3%B1%C3%ADa%20main%20facade.jpg?width=1920'],
['Centro Histórico','Se recorre a pie','Made for walking','https://commons.wikimedia.org/wiki/Special:Redirect/file/Historic%20Center%20of%20Quito%2C%20street%20scene.b1.jpg?width=1920']] as const;
const E=[['Cotopaxi','https://commons.wikimedia.org/wiki/Special:Redirect/file/Cotopaxi%20Volcano.jpg?width=1920'],['Quilotoa','https://commons.wikimedia.org/wiki/Special:Redirect/file/Panorama%20quilotoa%20crater%20lake%20ecuador.jpg?width=1920'],['Otavalo','https://commons.wikimedia.org/wiki/Special:Redirect/file/Otavalo%20Ecuador%201684.jpg?width=1920'],['Papallacta','https://commons.wikimedia.org/wiki/Special:Redirect/file/Laguna%20de%20Papallacta.jpg?width=1920'],['Baños','https://commons.wikimedia.org/wiki/Special:Redirect/file/Pail%C3%B3n%20del%20Diablo%2C%20cerca%20a%20Ba%C3%B1os%2C%20Ecuador%20%283258%29.jpg?width=1920']] as const;
const G=[['ANDES','https://commons.wikimedia.org/wiki/Special:Redirect/file/Vista%20panor%C3%A1mica%20del%20Nevado%20Chimborazo%20desde%20Luisa.JPG?width=1600'],['AMAZONÍA','https://commons.wikimedia.org/wiki/Special:Redirect/file/Reserva%20Faun%C3%ADstica%20de%20Cuyabeno%20%28Amazonia%20ecuatoriana%29%20%2820324137164%29.jpg?width=1600'],['COSTA','https://commons.wikimedia.org/wiki/Special:Redirect/file/Playa%20Los%20Frailes.jpg?width=1600'],['GALÁPAGOS','https://commons.wikimedia.org/wiki/Special:Redirect/file/Gal%C3%A1pagos%20beach.jpg?width=1600']] as const;
const WA='https://wa.me/593982023389',IG='https://www.instagram.com/hostalmialeticia/';
const c=(v:number)=>Math.max(0,Math.min(1,v));
export default function V2(){
 const[en,setEn]=useState(false),[menu,setMenu]=useState(false),[room,setRoom]=useState(0),[dest,setDest]=useState(0);const rr=useRef(0),dr=useRef(0);const t=(es:string,eng:string)=>en?eng:es;
 useEffect(()=>{document.body.classList.toggle('menu-open',menu);return()=>document.body.classList.remove('menu-open')},[menu]);
 useEffect(()=>{let raf=0;const paint=()=>{const total=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--progress',String(total?scrollY/total:0));document.querySelectorAll<HTMLElement>('[data-scene]').forEach(s=>{const r=s.getBoundingClientRect(),p=c(-r.top/Math.max(s.offsetHeight-innerHeight,1));s.style.setProperty('--p',p.toFixed(4));s.querySelectorAll<HTMLElement>('[data-window]').forEach(i=>{const[a=0,b=1]=(i.dataset.window?.split(':').map(Number)||[]),f=Math.min(.09,Math.max((b-a)/3,.025));i.style.setProperty('--w',c(Math.min((p-a)/f,(b-p)/f)).toFixed(4))});if(s.dataset.scene==='rooms'){const n=Math.min(3,Math.floor(p*4));if(n!==rr.current){rr.current=n;setRoom(n)}}if(s.dataset.scene==='ecuador'){const n=Math.min(4,Math.floor(p*5));if(n!==dr.current){dr.current=n;setDest(n)}}});raf=0};const go=()=>{if(!raf)raf=requestAnimationFrame(paint)},pointer=(e:PointerEvent)=>{const x=e.clientX/innerWidth,y=e.clientY/innerHeight;document.documentElement.style.setProperty('--mx',String(x-.5));document.documentElement.style.setProperty('--my',String(y-.5));document.documentElement.style.setProperty('--px',`${(x*100).toFixed(2)}%`);document.documentElement.style.setProperty('--py',`${(y*100).toFixed(2)}%`)};paint();addEventListener('scroll',go,{passive:true});addEventListener('resize',go,{passive:true});addEventListener('pointermove',pointer,{passive:true});return()=>{removeEventListener('scroll',go);removeEventListener('resize',go);removeEventListener('pointermove',pointer);if(raf)cancelAnimationFrame(raf)}},[]);
 const close=()=>setMenu(false),cur=R[room];
 return <main><div className="progress"/>
 <header className="masthead"><a className="brand" href="#top">MIA LETICIA</a><nav className="quick-nav"><a href="#casa">{t('Casa','House')}</a><a href="#habitaciones">{t('Habitaciones','Rooms')}</a><a href="#quito">Quito</a><a href="#ecuador">Ecuador</a><a href="#galeria">{t('Galería','Gallery')}</a></nav><div className="mast-tools"><button onClick={()=>setEn(!en)}>{en?'ES':'EN'}</button><a className="mast-book" href={WA} target="_blank" rel="noreferrer">{t('RESERVAR','BOOK')} ↗</a><button className="menu-toggle" onClick={()=>setMenu(true)}>{t('Menú','Menu')}</button></div></header>
 <aside className={`site-menu ${menu?'open':''}`} aria-hidden={!menu}><button className="menu-close" onClick={close}>{t('Cerrar','Close')} ×</button><div className="menu-inner"><p>MIA LETICIA · QUITO</p><nav><a href="#casa" onClick={close}>{t('La casa','The house')}</a><a href="#habitaciones" onClick={close}>{t('Habitaciones','Rooms')}</a><a href="#quito" onClick={close}>Quito</a><a href="#ecuador" onClick={close}>Ecuador</a><a href="#galeria" onClick={close}>{t('Galería','Gallery')}</a><a href="#contacto" onClick={close}>{t('Contacto','Contact')}</a></nav><a className="menu-book" href={WA} target="_blank" rel="noreferrer">{t('RESERVAR ESTANCIA','BOOK YOUR STAY')} ↗</a><a className="menu-instagram" href={IG} target="_blank" rel="noreferrer">Instagram @hostalmialeticia ↗</a></div></aside>
 <section className="hero" id="top"><img src="images/facade.webp" alt="Fachada de Mía Leticia"/><div className="shade"/><p className="folio">QUITO · ECUADOR</p><h1><span>{t('Tu puerta','Your door')}</span><em>{t('de entrada','into')}</em><span>{t('a Ecuador.','Ecuador.')}</span></h1><p className="dek">{t('Una casa colonial en el corazón del Centro Histórico de Quito.','A colonial house in the heart of Quito’s Historic Centre.')}<br/>{t('A tres cuadras de Plaza Grande.','Three blocks from Plaza Grande.')}</p><a className="enter" href="#llegada">{t('Descubrir','Discover')} ↓</a></section>
 <section className="ml-arrival" id="llegada" data-scene="arrival"><div className="ml-stage ml-arrival-stage"><div className="ml-small-photo ml-arrival-photo"><img src={S.arrival} alt="Viajeros llegando a Mía Leticia"/></div><p className="ml-kicker">00 — {t('LLEGADA','ARRIVAL')}</p><h2 className="ml-arrival-copy"><span className="ml-window" data-window=".08:.52">{t('Llegas al corazón de Quito.','You arrive in the heart of Quito.')}</span><em className="ml-window" data-window=".47:.92">{t('Y entras a la casa.','And you enter the house.')}</em></h2><p className="ml-window ml-arrival-address" data-window=".68:.98">Montúfar N5-91 y Mejía · Centro Histórico</p></div></section>
 <section className="ml-patio" id="casa" data-scene="patio"><div className="ml-stage ml-patio-stage"><img src="images/hero-patio.webp" alt="Patio colonial de Mía Leticia"/><div className="ml-cursor-light"/><p className="ml-kicker">01 — {t('LA CASA','THE HOUSE')}</p><h2 className="ml-window ml-patio-title" data-window=".08:.50"><span>{t('Ya estás','You are')}</span><em>{t('en casa.','home.')}</em></h2><p className="ml-window ml-patio-copy" data-window=".50:.90">{t('Una casa colonial hecha para recibir, en pleno Centro Histórico.','A colonial house made for hospitality, right in the Historic Centre.')}</p></div></section>
 <section className="ml-life" data-scene="life"><div className="ml-stage ml-life-stage"><p className="ml-kicker">02 — {t('VIDA EN LA CASA','LIFE IN THE HOUSE')}</p>
 <article className="ml-window ml-life-beat beat-breakfast" data-window="0:.35"><div className="ml-small-photo"><img src={S.breakfast} alt="Desayuno en Mía Leticia"/></div><div><small>08:00 — 10:00</small><h2>{t('La mañana empieza aquí.','The morning starts here.')}</h2></div></article>
 <article className="ml-window ml-life-beat beat-games" data-window=".32:.68"><div className="ml-small-photo"><img src={S.games} alt="Huéspedes jugando"/></div><div><h2>{t('Hay tiempo para quedarse un poco.','There is time to stay a little.')}</h2><p>{t('Conversar. Jugar. Compartir.','Talk. Play. Share.')}</p></div></article>
 <article className="ml-window ml-life-beat beat-family" data-window=".65:.99"><div className="ml-small-photo"><img src={S.family} alt="Familia hospedada en Mía Leticia"/></div><div><h2>{t('Cada viaje se vive distinto.','Every trip is lived differently.')}</h2><p>{t('Solo, en pareja, con amigos o en familia.','Solo, as a couple, with friends or as a family.')}</p></div></article></div></section>
 <section className="ml-rooms" id="habitaciones" data-scene="rooms"><div className="ml-stage ml-rooms-stage"><div className="ml-room-image"><img src={cur[2]} alt={`Habitación ${cur[0]}`}/><img className="ml-room-reveal" src={cur[2]} alt=""/></div><div className="ml-room-shade"/><p className="ml-kicker">03 — {t('HABITACIONES','ROOMS')}</p><h2 className="ml-room-title">{t('Dormir aquí.','Sleep here.')}</h2><nav className="ml-room-nav">{R.map((r,i)=><button key={r[0]} className={room===i?'active':''} onMouseEnter={()=>{rr.current=i;setRoom(i)}} onFocus={()=>{rr.current=i;setRoom(i)}} onClick={()=>{rr.current=i;setRoom(i)}}><small>0{i+1}</small><span>{en?r[1]:r[0]}</span></button>)}</nav><p className="ml-room-meta">{t('Baño privado · ducha caliente · desayuno incluido','Private bathroom · hot shower · breakfast included')}</p></div></section>
 <section className="ml-morning" data-scene="morning"><div className="ml-stage ml-morning-stage"><img className="ml-morning-room" src={R[1][2]} alt="Habitación al despertar"/><img className="ml-morning-city" src={Q[3][3]} alt="Centro Histórico de Quito"/><div className="ml-morning-shade"/><div className="ml-window ml-small-photo ml-morning-guest" data-window=".07:.48"><img src={S.morning} alt="Huéspedes por la mañana"/></div><span className="ml-window ml-clock" data-window=".02:.30">07:12</span><h2 className="ml-window ml-morning-line one" data-window=".10:.48">{t('Despierta.','Wake up.')}</h2><h2 className="ml-window ml-morning-line two" data-window=".52:.91">{t('Quito está a unos pasos.','Quito is a few steps away.')}</h2></div></section>
 <section className="ml-quito" id="quito" data-scene="quito"><div className="ml-stage ml-quito-stage">{Q.map((q,i)=><img key={q[0]} className="ml-window ml-quito-image" data-window={`${Math.max(0,i/4-.015)}:${Math.min(1,(i+1)/4+.025)}`} src={q[3]} alt={q[0]}/>)}<div className="ml-quito-mask"/><div className="ml-route"><i/></div>{Q.map((q,i)=><p key={q[0]} className="ml-window ml-quito-label" data-window={`${i/4+.02}:${Math.max(i/4+.10,(i+1)/4-.015)}`}><small>{en?q[2]:q[1]}</small>{q[0]}</p>)}<p className="ml-quito-close">{t('Desde Mía Leticia, Quito se camina.','From Mía Leticia, Quito is made for walking.')}</p><b className="ml-quito-word">QUITO</b></div></section>
 <section className="ml-journey" data-scene="journey"><div className="ml-stage ml-journey-stage"><img src={Q[3][3]} alt="Quito"/><div className="ml-journey-shade"/><h2><span className="ml-window" data-window=".08:.56">{t('Y desde Quito,','And from Quito,')}</span><em className="ml-window" data-window=".45:.94">{t('el viaje continúa.','the journey continues.')}</em></h2><div className="ml-journey-line"><i/></div></div></section>
 <section className="ml-ecuador" id="ecuador" data-scene="ecuador"><div className="ml-stage ml-ecuador-stage">{E.map((e,i)=><img key={e[0]} className="ml-window ml-ecuador-image" data-window={`${Math.max(0,i/5-.015)}:${Math.min(1,(i+1)/5+.02)}`} src={e[1]} alt={e[0]}/>)}<div className="ml-ecuador-shade"/><p className="ml-kicker">04 — ECUADOR</p><div className="ml-ecuador-track">{E.map((e,i)=><button key={e[0]} className={dest===i?'active':''} onMouseEnter={()=>{dr.current=i;setDest(i)}}>{e[0]}</button>)}</div><p className="ml-ecuador-copy">{t('Desde Quito, Ecuador se abre en todas direcciones.','From Quito, Ecuador opens in every direction.')}</p><span className="ml-ecuador-index">0{dest+1} / 05</span></div></section>
 <section className="ml-regions"><div className="ml-regions-grid">{G.map(g=><article className="ml-region" key={g[0]}><img loading="lazy" src={g[1]} alt={g[0]}/><div/><span>{g[0]}</span></article>)}</div><h2>{t('Cuatro regiones. Un país entero por recorrer.','Four regions. An entire country to explore.')}</h2></section>
 <section className="ml-gallery" id="galeria"><div className="ml-gallery-head"><p>05 — {t('GALERÍA','GALLERY')}</p><h2>{t('La casa, vivida.','The house, lived.')}</h2><a href={IG} target="_blank" rel="noreferrer">@hostalmialeticia ↗</a></div><div className="ml-gallery-grid"><a href={IG} target="_blank" rel="noreferrer"><img src={S.guests} alt="Huéspedes"/><span>{t('Huéspedes','Guests')}</span></a><a href={IG} target="_blank" rel="noreferrer"><img src="images/house-gallery.webp" alt="La casa"/><span>{t('La casa','The house')}</span></a><a href={IG} target="_blank" rel="noreferrer"><img src="images/detail.webp" alt="Detalles"/><span>{t('Detalles','Details')}</span></a></div><p className="ml-gallery-note">{t('Más momentos en Instagram.','More moments on Instagram.')}</p></section>
 <section className="ml-return" id="reserva" data-scene="return"><div className="ml-stage ml-return-stage"><div className="ml-small-photo ml-return-photo"><img src={S.ret} alt="Pareja de huéspedes"/></div><div className="ml-return-shade"/><h2 className="ml-window ml-return-one" data-window=".05:.40">{t('Sales a descubrir.','Go out and discover.')}</h2><h2 className="ml-window ml-return-two" data-window=".34:.68">{t('Vuelves a descansar.','Come back to rest.')}</h2><h2 className="ml-window ml-return-three" data-window=".62:.88">{t('Mañana, otra ruta.','Tomorrow, another route.')}</h2><div className="ml-window ml-final-book" data-window=".80:.99"><small>{t('TU BASE EN QUITO','YOUR BASE IN QUITO')}</small><h3>{t('Haz de Quito tu punto de partida.','Make Quito your starting point.')}</h3><p>{t('Reserva tu estancia en Mía Leticia.','Book your stay at Mía Leticia.')}</p><a href={WA} target="_blank" rel="noreferrer">{t('RESERVAR AHORA','BOOK NOW')} ↗</a></div><footer id="contacto"><b>MIA LETICIA</b><span>Montúfar N5-91 y Mejía · Quito</span><span>+593 98 202 3389 · info@mialeticia.com</span><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></footer></div></section>
 <div className="photo-credits">{t('Fotografía de destinos:','Destination photography:')} Wikimedia Commons · <a href="https://commons.wikimedia.org/" target="_blank" rel="noreferrer">{t('créditos y licencias','credits and licenses')} ↗</a></div>
 </main>
}
