'use client';
import {useEffect,useRef,useState} from 'react';
const R=[
['Simple','Single','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/6548b2e8.jpg?h=1100&impolicy=fcrop&w=1800'],
['Doble','Double','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/93710469.jpg?h=1100&impolicy=fcrop&w=1800'],
['Triple','Triple','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/b46d55e9.jpg?h=1100&impolicy=fcrop&w=1800'],
['Familiar','Family','https://images.trvl-media.com/lodging/4000000/3840000/3836700/3836630/b4288bf3.jpg?h=1100&impolicy=fcrop&w=1800']] as const;
const S={arrival:'images/social/arrival.webp',breakfast:'images/social/breakfast.webp',games:'images/social/games.webp',family:'images/social/family.webp',morning:'images/social/morning.webp',guests:'images/social/guests.webp',ret:'images/social/return.webp'};
const Q=[
['Plaza Grande','3 cuadras','3 blocks','https://commons.wikimedia.org/wiki/Special:Redirect/file/Quito%20Plaza%20Independencia.jpg?width=1920'],
['Catedral Metropolitana','Centro Histórico','Historic Centre','https://commons.wikimedia.org/wiki/Special:Redirect/file/%28Catedral%20Metropolitana%2C%20Quito%29%20exterior%20%28pic.bb8%29.jpg?width=1920'],
['La Compañía','Barroco quiteño','Quito Baroque','https://commons.wikimedia.org/wiki/Special:Redirect/file/Quito%20Iglesia%20de%20La%20Compa%C3%B1%C3%ADa%20main%20facade.jpg?width=1920'],
['Centro Histórico','Se recorre a pie','Made for walking','https://commons.wikimedia.org/wiki/Special:Redirect/file/Historic%20Center%20of%20Quito%2C%20street%20scene.b1.jpg?width=1920']] as const;
const E=[['Cotopaxi','https://commons.wikimedia.org/wiki/Special:Redirect/file/Cotopaxi%20Volcano.jpg?width=1920'],['Quilotoa','https://commons.wikimedia.org/wiki/Special:Redirect/file/Panorama%20quilotoa%20crater%20lake%20ecuador.jpg?width=1920'],['Otavalo','https://commons.wikimedia.org/wiki/Special:Redirect/file/Otavalo%20Ecuador%201684.jpg?width=1920'],['Papallacta','https://commons.wikimedia.org/wiki/Special:Redirect/file/Laguna%20de%20Papallacta.jpg?width=1920'],['Baños','https://commons.wikimedia.org/wiki/Special:Redirect/file/Pail%C3%B3n%20del%20Diablo%2C%20cerca%20a%20Ba%C3%B1os%2C%20Ecuador%20%283258%29.jpg?width=1920']] as const;
const G=[['SIERRA','https://commons.wikimedia.org/wiki/Special:Redirect/file/Vista%20panor%C3%A1mica%20del%20Nevado%20Chimborazo%20desde%20Luisa.JPG?width=1600'],['AMAZONÍA','https://commons.wikimedia.org/wiki/Special:Redirect/file/Reserva%20Faun%C3%ADstica%20de%20Cuyabeno%20%28Amazonia%20ecuatoriana%29%20%2820324137164%29.jpg?width=1600'],['COSTA','https://commons.wikimedia.org/wiki/Special:Redirect/file/Playa%20Los%20Frailes.jpg?width=1600'],['GALÁPAGOS','https://commons.wikimedia.org/wiki/Special:Redirect/file/Gal%C3%A1pagos%20beach.jpg?width=1600']] as const;
const QD=[
['Caminas unas pocas cuadras y llegas al corazón político e histórico de la ciudad.','A short walk takes you to the political and historic heart of the city.'],
['La arquitectura empieza a contar otra parte de Quito.','Architecture begins to tell another side of Quito.'],
['Iglesias, plazas, fachadas, patios y siglos de historia aparecen uno detrás de otro mientras avanzas.','Churches, plazas, façades, courtyards and centuries of history appear one after another as you walk.'],
['Entrar en una iglesia porque la puerta estaba abierta. Doblar una esquina. Encontrar una plaza que no estaba en el plan.','Step into a church because the door was open. Turn a corner. Find a plaza that was never on the plan.']
] as const;
const ED=[
['Montaña, páramo y uno de los volcanes que definen el paisaje de los Andes ecuatorianos.','Mountain, páramo and one of the volcanoes that define Ecuador’s Andean landscape.'],
['Una laguna dentro de un cráter y una carretera que atraviesa pequeñas comunidades de la Sierra.','A crater lake reached by a road that crosses small communities in the highlands.'],
['Mercado, textiles, artesanía y una de las rutas más conocidas al norte de Quito.','Market, textiles, crafts and one of the best-known routes north of Quito.'],
['Montaña, agua termal y una pausa entre los Andes y la entrada hacia la Amazonía.','Mountain, thermal water and a pause between the Andes and the road toward the Amazon.'],
['Cascadas, montaña y una ciudad desde la que el paisaje empieza a transformarse otra vez.','Waterfalls, mountains and a town where the landscape begins to change again.']
] as const;
const WA='https://wa.me/593982023389',IG='https://www.instagram.com/hostalmialeticia/';
const c=(v:number)=>Math.max(0,Math.min(1,v));
export default function V2(){
 const[en,setEn]=useState(false),[menu,setMenu]=useState(false),[room,setRoom]=useState(0),[dest,setDest]=useState(0);const rr=useRef(0),dr=useRef(0);const t=(es:string,eng:string)=>en?eng:es;
 useEffect(()=>{document.body.classList.toggle('menu-open',menu);return()=>document.body.classList.remove('menu-open')},[menu]);
 useEffect(()=>{let raf=0;const paint=()=>{const total=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--progress',String(total?scrollY/total:0));document.querySelectorAll<HTMLElement>('[data-scene]').forEach(s=>{const r=s.getBoundingClientRect(),p=c(-r.top/Math.max(s.offsetHeight-innerHeight,1));s.style.setProperty('--p',p.toFixed(4));s.querySelectorAll<HTMLElement>('[data-window]').forEach(i=>{const[a=0,b=1]=(i.dataset.window?.split(':').map(Number)||[]),f=Math.min(.09,Math.max((b-a)/3,.025));i.style.setProperty('--w',c(Math.min((p-a)/f,(b-p)/f)).toFixed(4))});if(s.dataset.scene==='rooms'){const n=Math.min(3,Math.floor(p*4));if(n!==rr.current){rr.current=n;setRoom(n)}}if(s.dataset.scene==='ecuador'){const n=Math.min(4,Math.floor(p*5));if(n!==dr.current){dr.current=n;setDest(n)}}});raf=0};const go=()=>{if(!raf)raf=requestAnimationFrame(paint)},pointer=(e:PointerEvent)=>{const x=e.clientX/innerWidth,y=e.clientY/innerHeight;document.documentElement.style.setProperty('--mx',String(x-.5));document.documentElement.style.setProperty('--my',String(y-.5));document.documentElement.style.setProperty('--px',`${(x*100).toFixed(2)}%`);document.documentElement.style.setProperty('--py',`${(y*100).toFixed(2)}%`)};paint();addEventListener('scroll',go,{passive:true});addEventListener('resize',go,{passive:true});addEventListener('pointermove',pointer,{passive:true});return()=>{removeEventListener('scroll',go);removeEventListener('resize',go);removeEventListener('pointermove',pointer);if(raf)cancelAnimationFrame(raf)}},[]);
 const close=()=>setMenu(false),cur=R[room];
 return <main><div className="progress"/>
 <header className="masthead"><a className="brand" href="#top">MIA LETICIA</a><nav className="quick-nav"><a href="#casa">{t('Casa','House')}</a><a href="#habitaciones">{t('Habitaciones','Rooms')}</a><a href="#quito">Quito</a><a href="#ecuador">Ecuador</a><a href="#galeria">{t('Galería','Gallery')}</a></nav><div className="mast-tools"><button onClick={()=>setEn(!en)}>{en?'ES':'EN'}</button><a className="mast-book" href={WA} target="_blank" rel="noreferrer">{t('RESERVAR','BOOK')} ↗</a><button className="menu-toggle" onClick={()=>setMenu(true)}>{t('Menú','Menu')}</button></div></header>
 <aside className={`site-menu ${menu?'open':''}`} aria-hidden={!menu}><button className="menu-close" onClick={close}>{t('Cerrar','Close')} ×</button><div className="menu-inner"><p>MIA LETICIA · QUITO</p><nav><a href="#casa" onClick={close}>{t('La casa','The house')}</a><a href="#habitaciones" onClick={close}>{t('Habitaciones','Rooms')}</a><a href="#quito" onClick={close}>Quito</a><a href="#ecuador" onClick={close}>Ecuador</a><a href="#galeria" onClick={close}>{t('Galería','Gallery')}</a><a href="#como-llegar" onClick={close}>{t('Cómo llegar','Getting here')}</a><a href="#contacto" onClick={close}>{t('Contacto','Contact')}</a></nav><a className="menu-book" href={WA} target="_blank" rel="noreferrer">{t('RESERVAR ESTANCIA','BOOK YOUR STAY')} ↗</a><a className="menu-instagram" href={IG} target="_blank" rel="noreferrer">Instagram @hostalmialeticia ↗</a></div></aside>
 <section className="hero" id="top"><img src="images/facade.webp" alt="Fachada de Mía Leticia"/><div className="shade"/><p className="folio">QUITO · ECUADOR</p><h1><span>{t('Tu puerta','Your door')}</span><em>{t('de entrada','into')}</em><span>{t('a Ecuador.','Ecuador.')}</span></h1><p className="dek">{t('Una casa colonial en el corazón del Centro Histórico de Quito.','A colonial house in the heart of Quito’s Historic Centre.')}</p><a className="enter" href="#llegada">{t('Descubrir','Discover')} ↓</a></section>
 <section className="ml-arrival" id="llegada" data-scene="arrival"><div className="ml-stage ml-arrival-stage"><div className="ml-small-photo ml-arrival-photo"><img src={S.arrival} alt="Viajeros llegando a Mía Leticia"/></div><p className="ml-kicker">01 — {t('LLEGADA','ARRIVAL')}</p><h2 className="ml-arrival-copy"><span className="ml-window" data-window=".06:.46">{t('Llegas a Ecuador.','You arrive in Ecuador.')}</span><em className="ml-window" data-window=".38:.78">{t('Esta es la casa que te recibe.','This is the house that welcomes you.')}</em></h2><div className="ml-window ml-arrival-body" data-window=".68:.98"><p>{t('Para muchos viajeros, Quito es el comienzo del recorrido. Mía Leticia es ese primer lugar donde dejar las maletas, detenerse un momento y empezar a entender dónde has llegado.','For many travellers, Quito is where the journey begins. Mía Leticia is that first place to leave your bags, pause for a moment and begin to understand where you have arrived.')}</p><strong>{t('Tu primera estancia. Tu primera puerta. El comienzo del viaje.','Your first stay. Your first door. The beginning of the journey.')}</strong></div></div></section>
 <section className="ml-patio" id="casa" data-scene="patio"><div className="ml-stage ml-patio-stage"><img src="images/hero-patio.webp" alt="Patio colonial de Mía Leticia"/><div className="ml-cursor-light"/><p className="ml-kicker">02 — {t('LA CASA','THE HOUSE')}</p><h2 className="ml-window ml-patio-title" data-window=".05:.42"><span>{t('Una casa que','A house revealed')}</span><em>{t('se descubre al recorrerla.','as you move through it.')}</em></h2><p className="ml-window ml-patio-copy" data-window=".35:.67">{t('Madera, adobe y hierro forjado conservan el carácter de una construcción que ha cambiado con el tiempo sin perder aquello que la hace reconocible.','Wood, adobe and wrought iron preserve the character of a building that has changed over time without losing what makes it recognisable.')}</p><p className="ml-window ml-patio-copy ml-patio-copy-two" data-window=".62:.86">{t('A su alrededor aparecen corredores, habitaciones, plantas, escaleras y pequeños espacios donde sentarse o simplemente detenerse.','Around it are corridors, rooms, plants, stairs and small places to sit or simply pause.')}</p><p className="ml-window ml-patio-close" data-window=".82:.99">{t('La casa se va revelando mientras la habitas.','The house reveals itself as you live in it.')}</p></div></section>
 <section className="ml-life" data-scene="life"><div className="ml-stage ml-life-stage"><p className="ml-kicker">03 — {t('QUIÉNES LLEGAN','WHO ARRIVES')}</p>
 <article className="ml-window ml-life-beat beat-solo" data-window=".01:.27"><div className="ml-small-photo"><img src={S.guests} alt="Huéspedes de Mía Leticia"/></div><div><small>{t('CADA VIAJE EMPIEZA DISTINTO','EVERY JOURNEY STARTS DIFFERENTLY')}</small><h2>{t('Algunos llegan solos.','Some arrive alone.')}</h2><p>{t('Después de muchos kilómetros y con una ruta todavía por decidir.','After many kilometres, with a route still to be decided.')}</p></div></article>
 <article className="ml-window ml-life-beat beat-together" data-window=".24:.52"><div className="ml-small-photo"><img src={S.games} alt="Amigos compartiendo en Mía Leticia"/></div><div><h2>{t('Otros llegan juntos.','Others arrive together.')}</h2><p>{t('Parejas, amigos, viajeros que comparten el camino.','Couples, friends, travellers sharing the road.')}</p></div></article>
 <article className="ml-window ml-life-beat beat-family" data-window=".49:.76"><div className="ml-small-photo"><img src={S.family} alt="Familia hospedada en Mía Leticia"/></div><div><h2>{t('También llegan familias.','Families arrive too.')}</h2><p>{t('Con otros tiempos, otros planes y otra manera de recorrer la ciudad.','With different rhythms, different plans and another way of exploring the city.')}</p></div></article>
 <article className="ml-window ml-life-beat beat-shared" data-window=".73:.99"><div><small>{t('UNA MISMA CASA','ONE HOUSE')}</small><h2>{t('Por unos días, todos pasan por la misma casa.','For a few days, everyone passes through the same house.')}</h2></div></article></div></section>
 <section className="ml-rooms" id="habitaciones" data-scene="rooms"><div className="ml-stage ml-rooms-stage"><div className="ml-room-image"><img src={cur[2]} alt={`Habitación ${cur[0]}`}/><img className="ml-room-reveal" src={cur[2]} alt=""/></div><div className="ml-room-shade"/><p className="ml-kicker">04 — {t('HABITACIONES','ROOMS')}</p><h2 className="ml-room-title">{t('Dormir aquí.','Sleep here.')}</h2><nav className="ml-room-nav">{R.map((r,i)=><button key={r[0]} className={room===i?'active':''} onMouseEnter={()=>{rr.current=i;setRoom(i)}} onFocus={()=>{rr.current=i;setRoom(i)}} onClick={()=>{rr.current=i;setRoom(i)}}><small>0{i+1}</small><span>{en?r[1]:r[0]}</span></button>)}</nav><p className="ml-room-meta">{t('Baño privado · ducha caliente · desayuno incluido','Private bathroom · hot shower · breakfast included')}</p></div></section>
 <section className="ml-morning" data-scene="morning"><div className="ml-stage ml-morning-stage"><img className="ml-morning-room" src="images/reading-area.webp" alt="Área común de Mía Leticia"/><img className="ml-morning-city" src="images/room.webp" alt="Habitación de Mía Leticia"/><div className="ml-morning-shade"/><p className="ml-kicker ml-stay-kicker">05 — {t('TU ESTANCIA','YOUR STAY')}</p>
 <article className="ml-window ml-stay-beat stay-morning" data-window=".02:.27"><div className="ml-small-photo"><img src={S.breakfast} alt="Desayuno en Mía Leticia"/></div><div><small>{t('LA MAÑANA','MORNING')}</small><h2>{t('El día empieza aquí.','The day starts here.')}</h2><p>{t('Pan, café, té, chocolate y fruta de temporada forman parte del desayuno incluido en la estancia. Un momento para despertar, revisar la ruta y decidir por dónde empezar.','Bread, coffee, tea, chocolate and seasonal fruit are part of the breakfast included with your stay. A moment to wake up, check the route and decide where to begin.')}</p></div></article>
 <article className="ml-window ml-stay-beat stay-rest" data-window=".24:.50"><div><small>{t('DESCANSAR','REST')}</small><h2>{t('Después de caminar, vuelves.','After walking, you come back.')}</h2><p>{t('Habitaciones con baño privado y ducha caliente, Wi-Fi y el espacio necesario para bajar el ritmo antes del siguiente día.','Rooms with private bathroom and hot shower, Wi-Fi and the space you need to slow down before the next day.')}</p></div></article>
 <article className="ml-window ml-stay-beat stay-help" data-window=".48:.74"><div><small>{t('SENTIRSE ACOMPAÑADO','HELP WHEN YOU NEED IT')}</small><h2>{t('Viajar también significa preguntar.','Travel also means asking questions.')}</h2><p>{t('La recepción permanece disponible las 24 horas y puede ayudarte con información turística y con aquello que necesites durante tu estancia.','Reception is available 24 hours a day and can help with tourist information and what you need during your stay.')}</p></div></article>
 <article className="ml-window ml-stay-beat stay-pause" data-window=".72:.99"><div className="ml-small-photo"><img src={S.games} alt="Espacios compartidos de Mía Leticia"/></div><div><small>{t('QUEDARSE UN POCO','STAY A LITTLE')}</small><h2>{t('No siempre hay que salir inmediatamente.','You do not always have to go out immediately.')}</h2><p>{t('Un libro. Una partida. Una conversación. Un café antes de continuar. Hay momentos del viaje que también ocurren dentro.','A book. A game. A conversation. A coffee before continuing. Some parts of the journey happen inside too.')}</p></div></article></div></section>
 <section className="ml-quito" id="quito" data-scene="quito"><div className="ml-stage ml-quito-stage">{Q.map((q,i)=><img key={q[0]} className="ml-window ml-quito-image" data-window={String(Math.max(0,i/4-.015))+':'+String(Math.min(1,(i+1)/4+.025))} src={q[3]} alt={q[0]}/>)}<div className="ml-quito-mask"/><p className="ml-kicker ml-quito-kicker">06 — {t('EL CENTRO HISTÓRICO, A PIE','THE HISTORIC CENTRE, ON FOOT')}</p><div className="ml-route"><i/></div>{Q.map((q,i)=><article key={q[0]} className="ml-window ml-quito-label" data-window={String(i/4+.02)+':'+String(Math.max(i/4+.10,(i+1)/4-.015))}><small>{en?q[2]:q[1]}</small><strong>{q[0]}</strong><span>{en?QD[i][1]:QD[i][0]}</span></article>)}<p className="ml-quito-close">{t('Desde Mía Leticia, esa parte de Quito empieza al salir por la puerta.','From Mía Leticia, this part of Quito begins the moment you step outside.')}</p><b className="ml-quito-word">QUITO</b></div></section>
 <section className="ml-journey" data-scene="journey"><div className="ml-stage ml-journey-stage"><img src="images/quito-panorama.webp" alt="Panorama de Quito"/><div className="ml-journey-shade"/><p className="ml-kicker ml-journey-kicker">07 — {t('QUITO SE ABRE','QUITO OPENS UP')}</p>
 <article className="ml-window ml-journey-beat journey-intro" data-window=".02:.29"><h2>{t('El Centro Histórico puede ocupar un día entero.','The Historic Centre can fill an entire day.')}</h2><p>{t('Pero la ciudad continúa.','But the city continues.')}</p></article>
 <article className="ml-window ml-journey-beat journey-up" data-window=".26:.52"><small>{t('SUBIR','GO UP')}</small><h2>{t('El Teleférico cambia la escala.','The cable car changes the scale.')}</h2><p>{t('La ciudad queda abajo y los Andes aparecen alrededor.','The city falls below and the Andes appear around you.')}</p></article>
 <article className="ml-window ml-journey-beat journey-out" data-window=".49:.74"><small>{t('ALEJARSE','GO FURTHER')}</small><h2>{t('Hacia el norte, la Mitad del Mundo.','To the north, the Middle of the World.')}</h2><p>{t('Barrios, mercados, miradores, parques y museos empiezan a ampliar el mapa.','Neighbourhoods, markets, viewpoints, parks and museums begin to expand the map.')}</p></article>
 <article className="ml-window ml-journey-beat journey-close" data-window=".71:.98"><h2>{t('Quito ya no es solamente el lugar al que llegaste.','Quito is no longer only the place where you arrived.')}</h2><p>{t('Empieza a convertirse en el lugar desde donde puedes ir mucho más lejos.','It becomes the place from which you can go much further.')}</p></article><div className="ml-journey-line"><i/></div></div></section>
 <section className="ml-ecuador" id="ecuador" data-scene="ecuador"><div className="ml-stage ml-ecuador-stage">{E.map((e,i)=><img key={e[0]} className="ml-window ml-ecuador-image" data-window={String(Math.max(0,i/5-.015))+':'+String(Math.min(1,(i+1)/5+.02))} src={e[1]} alt={e[0]}/>)}<div className="ml-ecuador-shade"/><p className="ml-kicker">08 — {t('DESDE QUITO','FROM QUITO')}</p><p className="ml-ecuador-intro">{t('Hay un momento en que el viaje deja atrás la ciudad. Y el paisaje cambia.','There comes a moment when the journey leaves the city behind. And the landscape changes.')}</p><div className="ml-ecuador-track">{E.map((e,i)=><button key={e[0]} className={dest===i?'active':''} onMouseEnter={()=>{dr.current=i;setDest(i)}}>{e[0]}</button>)}</div><p className="ml-ecuador-copy">{en?ED[dest][1]:ED[dest][0]}</p><p className="ml-ecuador-close">{t('Todos son viajes distintos. Y todos pueden empezar desde Quito.','Every journey is different. And every one of them can begin in Quito.')}</p><span className="ml-ecuador-index">0{dest+1} / 05</span></div></section>
 <section className="ml-regions" data-scene="regions"><div className="ml-stage ml-regions-stage"><p className="ml-kicker">09 — {t('UN PAÍS, CUATRO REGIONES','ONE COUNTRY, FOUR REGIONS')}</p><p className="ml-regions-intro">{t('Aquí ya no seguimos una ruta. Abrimos el mapa completo.','Here we stop following a single route. We open the whole map.')}</p><div className="ml-regions-grid">{G.map((g,i)=><article className="ml-region" key={g[0]}><img loading="lazy" src={g[1]} alt={g[0]}/><div/><span>{en?['HIGHLANDS','AMAZON','COAST','GALÁPAGOS'][i]:g[0]}</span></article>)}</div><h2>{t('Cuatro regiones. Un país entero por recorrer.','Four regions. An entire country to explore.')}</h2></div></section>
 <section className="ml-return" data-scene="return"><div className="ml-stage ml-return-stage"><div className="ml-small-photo ml-return-photo"><img src={S.ret} alt="Huéspedes regresando a Mía Leticia"/></div><div className="ml-return-shade"/><p className="ml-kicker">10 — {t('VOLVER','RETURN')}</p>
 <article className="ml-window ml-return-beat return-one" data-window=".03:.28"><h2>{t('Sales a descubrir.','You go out to discover.')}</h2><p>{t('A veces caminas unas cuadras.','Sometimes you walk a few blocks.')}</p></article>
 <article className="ml-window ml-return-beat return-two" data-window=".25:.51"><h2>{t('A veces llegas mucho más lejos.','Sometimes you go much further.')}</h2><p>{t('Una montaña. Otra ciudad. Otro paisaje.','A mountain. Another city. Another landscape.')}</p></article>
 <article className="ml-window ml-return-beat return-three" data-window=".48:.75"><p>{t('Y después de tantas cosas nuevas, hay algo sencillo que empieza a sentirse familiar:','And after so many new things, something simple begins to feel familiar:')}</p><h2>{t('volver.','coming back.')}</h2></article>
 <article className="ml-window ml-return-beat return-four" data-window=".72:.98"><p>{t('Regresas, dejas la mochila, descansas y vuelves a pensar en lo que viene.','You return, leave your bag, rest and begin thinking about what comes next.')}</p><h2>{t('Mañana puede empezar otra ruta.','Tomorrow another route can begin.')}</h2></article></div></section>
 <section className="ml-gallery" id="galeria"><div className="ml-gallery-head"><p>11 — {t('LA CASA, VIVIDA','THE HOUSE, LIVED')}</p><h2>{t('La casa, vivida.','The house, lived.')}</h2><a href={IG} target="_blank" rel="noreferrer">@hostalmialeticia ↗</a></div><p className="ml-gallery-intro">{t('Hasta aquí hemos contado una forma de recorrer Mía Leticia, Quito y Ecuador. Pero cada huésped termina construyendo la suya. Huéspedes, desayunos, encuentros, habitaciones, patios, familias, amigos y pequeños momentos cotidianos forman también parte de la historia de la casa.','So far we have told one way of moving through Mía Leticia, Quito and Ecuador. But every guest ends up building their own. Guests, breakfasts, encounters, rooms, courtyards, families, friends and small everyday moments are also part of the story of the house.')}</p><div className="ml-gallery-grid"><a href={IG} target="_blank" rel="noreferrer"><img src={S.guests} alt="Huéspedes"/><span>{t('Personas que llegaron','People who arrived')}</span></a><a href={IG} target="_blank" rel="noreferrer"><img src="images/house-gallery.webp" alt="La casa"/><span>{t('Momentos que ocurrieron aquí','Moments that happened here')}</span></a><a href={IG} target="_blank" rel="noreferrer"><img src="images/detail.webp" alt="Detalles"/><span>{t('Viajes que continuaron','Journeys that continued')}</span></a></div><p className="ml-gallery-note">{t('Más momentos en Instagram.','More moments on Instagram.')}</p></section>
 <section className="ml-directions" id="como-llegar" data-scene="directions"><div className="ml-stage ml-directions-stage"><img src="images/facade.webp" alt="Entrada de Mía Leticia"/><div className="ml-directions-shade"/><p className="ml-kicker">12 — {t('AHORA TE TOCA LLEGAR','NOW IT IS YOUR TURN TO ARRIVE')}</p><div className="ml-directions-title"><h2>{t('Ya sabes lo que hay detrás de la puerta.','Now you know what is behind the door.')}</h2><p>{t('Ahora falta llegar hasta ella.','Now you only have to get here.')}</p></div>
 <article className="ml-window ml-direction-beat direction-airport" data-window=".03:.24"><small>{t('DESDE EL AEROPUERTO','FROM THE AIRPORT')}</small><h3>{t('Aeropuerto → Mía Leticia','Airport → Mía Leticia')}</h3><p>{t('Mía Leticia ofrece servicio de traslado desde y hacia el Aeropuerto Internacional Mariscal Sucre. También puedes llegar por tu cuenta directamente hasta el Centro Histórico.','Mía Leticia offers transfer service to and from Mariscal Sucre International Airport. You can also make your own way directly to the Historic Centre.')}</p></article>
 <article className="ml-window ml-direction-beat direction-south" data-window=".21:.43"><small>{t('DESDE EL SUR','FROM THE SOUTH')}</small><h3>{t('Quitumbe → Centro Histórico → Mía Leticia','Quitumbe → Historic Centre → Mía Leticia')}</h3><p>{t('Si llegas a Quito en bus desde el sur del país, tu punto de entrada será el Terminal Terrestre Quitumbe.','If you arrive in Quito by bus from the south of the country, your point of entry will be Quitumbe bus terminal.')}</p></article>
 <article className="ml-window ml-direction-beat direction-north" data-window=".40:.62"><small>{t('DESDE EL NORTE','FROM THE NORTH')}</small><h3>{t('Carcelén → Centro Histórico → Mía Leticia','Carcelén → Historic Centre → Mía Leticia')}</h3><p>{t('Si vienes desde el norte de Ecuador, puedes llegar a través del Terminal Terrestre Carcelén.','If you are coming from northern Ecuador, you can arrive through Carcelén bus terminal.')}</p></article>
 <article className="ml-window ml-direction-beat direction-city" data-window=".59:.80"><small>{t('SI YA ESTÁS EN QUITO','IF YOU ARE ALREADY IN QUITO')}</small><h3>Montúfar N5-91 y Mejía.</h3><p>{t('En pleno Centro Histórico. Un mapa, la ruta y las opciones de transporte pueden acompañarte desde donde estés hasta la puerta.','Right in the Historic Centre. A map, route and transport options can guide you from wherever you are to the door.')}</p></article>
 <div className="ml-window ml-final-book" data-window=".77:.99"><small>{t('TU VIAJE PUEDE EMPEZAR AQUÍ','YOUR JOURNEY CAN BEGIN HERE')}</small><h3>{t('Una casa donde llegar. Quito al salir por la puerta. Ecuador entero por delante.','A house to arrive at. Quito outside the door. All of Ecuador ahead.')}</h3><p>{t('Reserva tu estancia en Mía Leticia.','Book your stay at Mía Leticia.')}</p><a href={WA} target="_blank" rel="noreferrer">{t('RESERVAR AHORA','BOOK NOW')} ↗</a></div><footer id="contacto"><b>MIA LETICIA</b><span>Montúfar N5-91 y Mejía · Quito</span><span>+593 98 202 3389 · info@mialeticia.com</span><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></footer></div></section>
 <div className="photo-credits">{t('Fotografía de destinos:','Destination photography:')} Wikimedia Commons · <a href="https://commons.wikimedia.org/" target="_blank" rel="noreferrer">{t('créditos y licencias','credits and licenses')} ↗</a></div>
 </main>
}
